### ISSUE TITLE
Grav 1.7 changes how the admin menu behaves

### ISSUE THREAD

**Issue by mahagr** [Flamenco/admin-power-tools#2]
In Grav 1.7 all the menu items (including Dashboard, Configuration, Pages...) are dynamically added to the menu and can be replaced with custom menu items.

This causes some issues with Admin Power Tools, which overrides the old template.

See Flex Objects plugin to see an example on how to override these menu items:
https://github.com/trilbymedia/grav-plugin-flex-objects/blob/develop/flex-objects.php#L280-L285

Here are the default menu items from the admin plugin:
https://github.com/getgrav/grav-plugin-admin/blob/1.10/admin.php#L734-L789

**Comment by Flamenco** [comment]
@mahagr When is the release date for 1.7?  We are currently debating whether to wrap/adapt the current behavior or continue to override the new templates.

**Comment by Flamenco** [comment]
@mahagr We updated our 4 overriden templates and added some version detection.  Thanks for the heads-up!

There are still some CSS issues as the new admin seems to have updated some items.

<img width="264" alt="Screen Shot 2019-09-20 at 3 46 50 PM" src="https://user-images.githubusercontent.com/819940/65354940-c6609b80-dbbe-11e9-9b55-82fb11c3a901.png">

The new version will be up in a day or so, after some testing.

**Comment by mahagr** [comment]
@Flamenco 

Sorry about my late response, my weekend was rather busy.

Grav 1.7 has no assigned release date yet, but it will be released this year, hopefully earlier than later.

**Comment by Flamenco** [comment]
Grav 1.7 and Admin have been addressed in our latest release.
