### ISSUE TITLE
Hard-coded /admin/ route breaks plugin where admin route is customised

### ISSUE THREAD

**Issue by RCheesley** [Flamenco/admin-power-tools#3]
Opening a new issue based on the comment here https://github.com/Flamenco/admin-power-tools/issues/1#issuecomment-595762196 given that the issue is closed.

I found multiple instances where this is hard-coded using /admin/ in the plugin:

* editpage.php line 93
* admin-power-tools.php lines 107, 290, 374, 422, 457, 462
* rename-page.php line 133

Guidance is given in the official Grav docs to change the default admin URL: https://learn.getgrav.org/16/admin-panel/faq#custom-admin-url for additional security.

I guess an option might be to look for the non-standard route in /user/config/plugins/admin.yaml and use a variable instead of hard-coding /admin/ in the paths?

**Comment by Flamenco** [comment]
This is our next bug to slay.  Thank you for posting.

**Comment by RCheesley** [comment]
Great, we had to disable the tool as a result of this problem!

**Comment by Flamenco** [comment]
I think we got them all in v0.1.14.  Please confirm and then reopen if it does not fix your problem.
