### ISSUE TITLE
PHP Warning: `preg_replace()`: No ending delimiter '-' found

### ISSUE THREAD

**Issue by NoNoNo** [Flamenco/admin-power-tools#5]
PHP Warning: `preg_replace()`: No ending delimiter '-' found in [classes/DependencyUtil.php:125](https://github.com/Flamenco/admin-power-tools/blob/master/classes/DependencyUtil.php#L125):

```php
                        $realVersion = preg_replace('-beta.*$','', $realVersion);
```

**Comment by Flamenco** [comment]
Fixed in v0.1.15
