### ISSUE TITLE
Does not work under PHP 7.4

### ISSUE THREAD

**Issue by otahirs** [Flamenco/admin-power-tools#6]
![Screenshot from 2020-11-02 12-54-28](https://user-images.githubusercontent.com/24588500/97865492-987adf80-1d0a-11eb-82ac-d82722d87123.png)

**Comment by Chia-KY** [comment]
Same issure for me with PHP 7.4. My way of fixing this for now. Edit '/user/plugins/admin-power-tools/classes/ReportUtil.php' line 139

**//return $config->grav['base_url_relative'] . $base;
return isset($config->grav['base_url_relative']) ? $config->grav['base_url_relative'] . $base : $base;**

**Comment by Flamenco** [comment]
thank you for the report. we will update the plugin ASAP

**Comment by planetar** [comment]
seconded, it crashed/gave the debugger immediately after installation. My way out was to downgrade to php7.3 which fixed the issue

**Comment by Flamenco** [comment]
@Chia-KY Was this the only issue you found after upgrading to PHP 7.4?  Have you tried Grav with PHP 8.0?

**Comment by Flamenco** [comment]
I installed a fresh version of grav in PHP 7.4 environment.  Then installed the power-tools+service-manager plugins.  No errors.  So the question is "why is your base_url_relative not set"?

Regardless, I will add the conditional to the next release.

**Comment by Flamenco** [comment]
Hey, we reproducted it!  Should be updated today.

**Comment by Flamenco** [comment]
Updated in latest release. Please confirm.
